
import telepot
import random
from libs.bot import Bot

class DogeKunBot(Bot):

    # Initializing variables
    def __init__(self):
        self.DCC_reference = "@diggo90"
        self.stickers = ['BQADAQADIgEAAtpvQgjYhzUC2GRFpQI',
                         'BQADBAADTAADqAABTgXzVqN6dJUIXwI',
                         'BQADBAADTgADqAABTgVwAsJg5JF13gI',
                         'BQADBAADUAADqAABTgWNDAwSG6JnrQI',
                         'BQADBAADUgADqAABTgWecdF3Lr8hCAI',
                         'BQADBAADVAADqAABTgUYtFwhmgdoeQI',
                         'BQADBAADVgADqAABTgXlG1-Srz3L1gI',
                         'BQADBAADWAADqAABTgVG3pN_piQYLwI',
                         'BQADBAADWgADqAABTgXq1aU5b-0s5wI',
                         'BQADBAADXAADqAABTgXk4diYnlhzqAI',
                         'BQADBAADXgADqAABTgUAAYNhxQFyMr0C',
                         'BQADBAADYAADqAABTgUOhrgP-sQligI',
                         'BQADBAADYgADqAABTgWxIHGehHx2CgI',
                         'BQADBAADZQADqAABTgXue196hCQaXQI',
                         'BQADBAADZwADqAABTgWkjlZH4FeNbAI',
                         'BQADBAADaQADqAABTgWtE38sqqiYZgI',
                         'BQADBAADawADqAABTgV1VlKqbfVqjwI',
                         'BQADBAADbQADqAABTgXfq9-TplxmDQI',
                         'BQADBAADbwADqAABTgXNZRd9w9n5UAI',
                         'BQADBAADcQADqAABTgVjKtJ4n0PeGQI',
                         'BQADBAADcwADqAABTgWjSGIedl17VQI',
                         'BQADBAADdQADqAABTgVCbT-MdM82eAI',
                         'BQADBAADdwADqAABTgX1eZz9Y9UFRgI',
                         'BQADBAADeQADqAABTgWtOTH-W4CbAwI',
                         'BQADBAADewADqAABTgXQyw0P5FkQFQI',
                         'BQADBAADfQADqAABTgVC6SC_GNTLCgI',
                         'BQADBAADfwADqAABTgWG3GKyJwsMIwI',
                         'BQADBAADjQADqAABTgXklIT2xPTbIAI',
                         'BQADBAADjwADqAABTgWev3HfSmWchQI',
                         'BQADBAADkgADqAABTgVUFVak54OTFgI',
                         'BQADBAADlQADqAABTgWdUcVlUD0xgAI',
                         'BQADBAADlwADqAABTgWtl6uoWtqGcgI',
                         'BQADBAADmgADqAABTgUVUzsvhQ548QI',
                         'BQADBAADnQADqAABTgUGC2HyO4KBmQI',
                         'BQADBAADoQADqAABTgU_DRXAGeGmQAI',
                         'BQADBAADpgADqAABTgUnMQ1LPqKoygI',
                         'BQADBAADuQADqAABTgU3uxeLh1QaUQI',
                         'BQADAQADRwEAAno8IghSB0DOblRitgI',
                         'BQADAQADSQEAAno8Igg0tvfreOxGSAI',
                         'BQADAQADgQEAAno8IghzUDPHt05juwI',
                         'BQADAQADSwEAAno8Igj7A50EV1yvMwI',
                         'BQADAQADTQEAAno8IgiUjTq85iJ5JwI',
                         'BQADAQADTwEAAno8Igj5T9a4RXDhygI',
                         'BQADAQADgwEAAno8IggtwnXSKcRSkgI',
                         'BQADAQADUQEAAno8IggBS4hdPbiWBgI',
                         'BQADAQADagEAAno8IgjbhRTGMeyCuAI',
                         'BQADAQADUwEAAno8Ighy-b-Q9AuCkAI',
                         'BQADAQADWQEAAno8Igh_3ffjxsT8BgI',
                         'BQADAQADWwEAAno8IghEbFQRn2szVwI',
                         'BQADAQADYgEAAno8IgitV9775V4O5QI',
                         'BQADAQADZAEAAno8IghXTD7a7yNH7QI',
                         'BQADAQADfwEAAno8IghT_7_Ohw1mHwI',
                         'BQADAQADaAEAAno8IghKvAEGwd468AI',
                         'BQADAQADbAEAAno8Igg9PJcm3tIKegI',
                         'BQADAQADbgEAAno8Igi-pckbSPmbEgI',
                         'BQADAQADcAEAAno8IgjPohl5xmsgiQI',
                         'BQADAQADcgEAAno8IgjS8l_cH_2KmQI',
                         'BQADAQADewEAAno8Igh3m_rUGCHcxQI',
                         'BQADAQADmwEAAno8Ighj84sUgq8iqQI',
                         'BQADAQADhQEAAno8IggtLN9BLoDOYQI',
                         'BQADAQADhwEAAno8IghmMlQhYAcaTgI',
                         'BQADAQADiQEAAno8IggI3VSqAY-gwwI',
                         'BQADAQADiwEAAno8IggqWr3FhnOt2QI',
                         'BQADAQADlAEAAno8Igiq-sav3Y6F4AI',
                         'BQADAQADmQEAAno8IgiY-GLLUWz-cQI',
                         'BQADAQADxwEAAno8Igg1fOCdfg_qPwI',
                         'BQADAQADdQEAAno8IgjnZzIH11f23QI',
                         'BQADAQADnQEAAno8Igg1MUAMDzGvWwI',
                         'BQADAQADnwEAAno8IgiUcrlQnlyj3AI',
                         'BQADAQADtAEAAno8IgiCAzMr7xAo0wI',
                         'BQADAQADwwEAAno8IgikXbp25GsqOQI',
                         'BQADAQADogEAAno8IggVcj41WEa1-gI',
                         'BQADAQADpQEAAno8IghP7S83hGz9XwI',
                         'BQADAQADpwEAAno8IghUoLtU7PoYOAI',
                         'BQADAQADqQEAAno8Igi3-yac_iXujwI',
                         'BQADAQADqwEAAno8Igih3kR_uKoasQI',
                         'BQADAQADxQEAAno8IghfAAFrufWlUNgC',
                         'BQADAQADrQEAAno8IggwAwABMsvLjiYC',
                         'BQADAQADugEAAno8Igiekr13gR_ZWwI',
                         'BQADAQADyQEAAno8IgjTnmver7tgUgI',
                         'BQADAQADzQEAAno8IgiQvvMdfXkHWAI',
                         'BQADAQADzwEAAno8IgiQKBUUkg2b1QI',
                         'BQADAQAD0QEAAno8IgjK_fFaLLbVOwI',
                         'BQADAQAD0wEAAno8IgheGrP4gzx0SAI',
                         'BQADAQAD1QEAAno8Igh4rqtGVRNApgI',
                         'BQADAQAD5AAD2m9CCFyHVexaxz8nAg',
                         'BQADAQAD5gAD2m9CCG-FQyzqVL7HAg',
                         'BQADAQAD6AAD2m9CCND58Ai0EGNnAg',
                         'BQADAQAD7AAD2m9CCHdwsIi84OA2Ag',
                         'BQADAQAD8AAD2m9CCFftG9zjrkGCAg',
                         'BQADAQAD8gAD2m9CCOT-LxXDWcVuAg',
                         'BQADAQAD-AAD2m9CCBoOGIvg3NK3Ag',
                         'BQADAQAD_gAD2m9CCJA-gKEO1ealAg',
                         'BQADAQAEAQAC2m9CCN6vg-Iu7EdCAg',
                         'BQADAQADAgEAAtpvQgipGV3wtiIXBAI',
                         'BQADAQADBgEAAtpvQggH_nV3qVWwagI',
                         'BQADAQADCAEAAtpvQgi7MKXXZi5H2AI',
                         'BQADAQADCgEAAtpvQghahyogeqFZuQI',
                         'BQADAQADDAEAAtpvQgi5WFYRgPulYwI',
                         'BQADAQADDgEAAtpvQghfRoGXQArCbQI',
                         'BQADAQADEAEAAtpvQghrw_C_3UFqZAI',
                         'BQADAQADEgEAAtpvQgjOvvKVAmKO6AI',
                         'BQADAQADFAEAAtpvQggeunJh0_p8pAI',
                         'BQADAQADFgEAAtpvQghnnl-RnszFMgI',
                         'BQADAQADGAEAAtpvQghVSsL8ITIqIgI',
                         'BQADAQADGgEAAtpvQgiW8AVNIdUd3AI',
                         'BQADAQADHAEAAtpvQghceIFyzQ-5_QI',
                         'BQADAQADHgEAAtpvQghx41UW9IlkhQI',
                         'BQADAQADIAEAAtpvQghTSIcifdHV0wI',
                         'BQADAQADIgEAAtpvQgjYhzUC2GRFpQI',
                         'BQADAQADYQEAAtpvQgjgWlTcrHsXmgI',
                         'BQADAQADYwEAAtpvQghTFZd-12-sYQI',
                         'BQADAQADZQEAAtpvQgjdOhhKOMDT2gI',
                         'BQADAQADZwEAAtpvQgioZfD8Gs0KdQI',
                         'BQADAQADaQEAAtpvQgiEPoJB7TO3uwI',
                         'BQADAQADawEAAtpvQggX42-d8yt_JgI',
                         'BQADAQADbQEAAtpvQggHy-7yeBEQ8gI',
                         'BQADAQADbwEAAtpvQggxmAQQVBxomwI',
                         'BQADAQADcQEAAtpvQghXkoNGUT-q7AI',
                         'BQADAQADcwEAAtpvQgjW7-XilDRRIQI',
                         'BQADAQADdQEAAtpvQgibrIRVAU3j1wI',
                         'BQADAQADdwEAAtpvQghvrtRduRSYXgI',
                         'BQADAQADeQEAAtpvQghutTEHyjP7BgI',
                         'BQADAQADewEAAtpvQghyER3lrdTrmgI',
                         'BQADAQADfQEAAtpvQgjpalMIYTxsTwI',
                         'BQADAQADfwEAAtpvQggbYQfZLLsAAbMC',
                         'BQADAQADgwEAAtpvQghUH_E3SbQZDQI',
                         'BQADAQADgQEAAtpvQggqv7nlXTWS-QI',
                         'BQADAQADcwADu4fbBRMB30cqXysbAg',
                         'BQADAQADdQADu4fbBeCky9q0I9NuAg',
                         'BQADAQADdwADu4fbBUGnZ0ulL-C-Ag',
                         'BQADAQADeQADu4fbBQNECbw7Vva3Ag',
                         'BQADAQADewADu4fbBeH0_Br1feF6Ag',
                         'BQADAQADfQADu4fbBarWZSVTp6BoAg',
                         'BQADAQADfwADu4fbBS86T5wEO1bZAg',
                         'BQADAQADgQADu4fbBVM2HxQAAUBtQgI',
                         'BQADAQADgwADu4fbBSIxZdoKqtoTAg',
                         'BQADAQADhQADu4fbBX1vGLvFui-3Ag',
                         'BQADAQADhwADu4fbBatmc-OMxZNqAg',
                         'BQADAQADiQADu4fbBUn7P9OuwGO1Ag',
                         'BQADAQADiwADu4fbBTx4wc8OlQ68Ag',
                         'BQADAQADjQADu4fbBWSuIwtLuu-jAg',
                         'BQADAQADjwADu4fbBXH0pfEO5X8pAg',
                         'BQADAQADkQADu4fbBcflU1lj8LrlAg',
                         'BQADAQADkwADu4fbBUK6CKBy1HijAg',
                         'BQADAQADlQADu4fbBV1HBiqubXbyAg',
                         'BQADAQADlwADu4fbBbUXRe_Qt9UpAg',
                         'BQADAQADmQADu4fbBXfH-yHvuTPxAg',
                         'BQADAQADmwADu4fbBfdRYqwuFodvAg',
                         'BQADAQADnQADu4fbBdm0u9irMkn-Ag'
                        ]

    # Definig act function
    def act(self, msg, bot):
        # How to get info of the message
        content_type, chat_type, chat_id = telepot.glance(msg)
        bot.sendSticker(chat_id = chat_id, sticker = random.choice(self.stickers), reply_to_message_id=msg['message_id'])
